services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    command: bash -c "rails db:migrate && rails db:seed && rails rails_env=test db:migrate && rails server -b 0.0.0.0"
  tailwind:
    build: .
    volumes:
      - "./:/app"
    command: rails tailwindcss:watch
    stdin_open: true
